[2024-01-02T20:47:58.026+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_into_table scheduled__2022-11-24T00:00:00+00:00 [queued]>
[2024-01-02T20:47:58.035+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_into_table scheduled__2022-11-24T00:00:00+00:00 [queued]>
[2024-01-02T20:47:58.035+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-01-02T20:47:58.055+0100] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): delete_into_table> on 2022-11-24 00:00:00+00:00
[2024-01-02T20:47:58.060+0100] {standard_task_runner.py:57} INFO - Started process 69573 to run task
[2024-01-02T20:47:58.068+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'delete_into_table', 'scheduled__2022-11-24T00:00:00+00:00', '--job-id', '14459', '--raw', '--subdir', '/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/methode-1/dags/dag_with_postgres.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmplvuzfu7f']
[2024-01-02T20:47:58.072+0100] {standard_task_runner.py:85} INFO - Job 14459: Subtask delete_into_table
[2024-01-02T20:47:58.132+0100] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.delete_into_table scheduled__2022-11-24T00:00:00+00:00 [running]> on host macbook-pro-de-user.local
[2024-01-02T20:47:58.845+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='delete_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-24T00:00:00+00:00'
[2024-01-02T20:47:58.846+0100] {sql.py:274} INFO - Executing: 
            delete from dag_runs where dt='2022-11-24' and dag_id='dag_with_postgres_operator_v04'
        
[2024-01-02T20:47:58.852+0100] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-02T20:47:59.072+0100] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-02T20:47:59.115+0100] {sql.py:418} INFO - Running statement: 
            delete from dag_runs where dt='2022-11-24' and dag_id='dag_with_postgres_operator_v04'
        , parameters: None
[2024-01-02T20:47:59.137+0100] {sql.py:427} INFO - Rows affected: 0
[2024-01-02T20:47:59.146+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=delete_into_table, execution_date=20221124T000000, start_date=20240102T194758, end_date=20240102T194759
[2024-01-02T20:47:59.209+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-02T20:47:59.253+0100] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
