[2024-01-02T20:33:24.662+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-10-09T00:00:00+00:00 [queued]>
[2024-01-02T20:33:24.668+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-10-09T00:00:00+00:00 [queued]>
[2024-01-02T20:33:24.668+0100] {taskinstance.py:1361} INFO - Starting attempt 3 of 6
[2024-01-02T20:33:24.679+0100] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-10-09 00:00:00+00:00
[2024-01-02T20:33:24.682+0100] {standard_task_runner.py:57} INFO - Started process 61928 to run task
[2024-01-02T20:33:24.688+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2022-10-09T00:00:00+00:00', '--job-id', '14258', '--raw', '--subdir', '/Users/user/Desktop/Learning/AIRFLOW-TUTORIAL/methode-1/dags/dag_with_postgres.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmpmcyj0hxr']
[2024-01-02T20:33:24.691+0100] {standard_task_runner.py:85} INFO - Job 14258: Subtask insert_into_table
[2024-01-02T20:33:24.740+0100] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-10-09T00:00:00+00:00 [running]> on host macbook-pro-de-user.local
[2024-01-02T20:33:25.282+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2022-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-10-09T00:00:00+00:00'
[2024-01-02T20:33:25.283+0100] {sql.py:274} INFO - Executing: 
            insert into dag_runs(dt, dag_id) values('2022-10-09','dag_with_postgres_operator_v03')
        
[2024-01-02T20:33:25.288+0100] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-02T20:33:25.460+0100] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-02T20:33:25.492+0100] {sql.py:418} INFO - Running statement: 
            insert into dag_runs(dt, dag_id) values('2022-10-09','dag_with_postgres_operator_v03')
        , parameters: None
[2024-01-02T20:33:25.495+0100] {sql.py:427} INFO - Rows affected: 1
[2024-01-02T20:33:25.502+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20221009T000000, start_date=20240102T193324, end_date=20240102T193325
[2024-01-02T20:33:25.532+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-02T20:33:25.548+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
